allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  better-sqlite3: true
  electron: true
  electron-winstaller: false
  esbuild: false
  ffmpeg-static: false
  less: false
  lmdb: false
  lzma-native: true
  msgpackr-extract: false
  nx: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - nx
